services:
  nest:
    image: node:20.14.0-alpine3.19
    restart: always
    command: sh -c 'npm i && npm run start:dev'
    working_dir: /app
    volumes:
      - ./nest:/app
    ports:
      - 3001:3000
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0.27-focal
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: GSgVAm73urNv
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/init:/docker-entrypoint-initdb.d/

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: GSgVAm73urNv
      ME_CONFIG_MONGODB_URL: mongodb://root:GSgVAm73urNv@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    ports:
      - 8081:8081
    depends_on:
      - mongo