version: '3'

tasks:

  #
  # docker
  #
  up:
    cmds:
      - docker compose up -d
  down:
    cmds:
      - docker compose down
  logs:
    cmds:
      - docker compose logs -f

  #
  # nest
  #
  npm:
    cmds:
      - docker compose exec nest npm {{.CLI_ARGS}}
  test:
    cmds:
      - clear
      - task npm -- run test
